# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 00:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='MateriaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivado', models.BooleanField(default=False)),
                ('precio', models.PositiveIntegerField(verbose_name='Precio por hora')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Materia')),
            ],
            options={
                'verbose_name': 'Materia Usuario',
                'verbose_name_plural': 'Materias Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivado', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('calificacion', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('fecha', models.DateField()),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('aprobada', models.BooleanField(default=False)),
                ('finalizada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='TematicaMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivado', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Materia')),
            ],
            options={
                'verbose_name': 'Tematica Materia',
                'verbose_name_plural': 'Tematicas Materias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivado', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Materia'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tematica',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='materia', chained_model_field='materia', on_delete=django.db.models.deletion.CASCADE, to='app.TematicaMateria'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='materiausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='materiausuario',
            unique_together=set([('materia', 'usuario')]),
        ),
    ]
