# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
