# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180305_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tematicamateria',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='tematica',
        ),
        migrations.DeleteModel(
            name='TematicaMateria',
        ),
    ]
