# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180307_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiausuario',
            name='precio',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio por hora'),
        ),
    ]
