# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180309_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='hora_final',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='hora_inicial',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
