# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180320_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='mensaje',
        ),
    ]
