# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_solicitud_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MateriaUsuario'),
        ),
    ]
