# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180320_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiausuario',
            name='oferta_aprobada',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
