# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_materiausuario_oferta_aprobada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='rechazada',
            field=models.BooleanField(default=False),
        ),
    ]
